language: node_js

node_js:
    - "6"

install:
    - npm install

script:
    - npm test
    - npm run production

after_success:
    - '[ "${TRAVIS_BRANCH}" = "deploy"] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash ./deploy.sh'
