language: node_js

node_js:
    - "6"

install:
    - npm install

script:
    - npm test
    - npm run production

after_success:
    - echo ${TRAVIS_BRANCH}
    - echo ${TRAVIS_PULL_REQUEST}
    - '[ "${TRAVIS_BRANCH}" = "deploy" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash ./deploy.sh'
